apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/srikanthpusunuri1234/canerytest.git'
    targetRevision: HEAD
    path: . # Points to the exact same engine
    helm:
      releaseName: frontend-service
      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true