apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        {{- if .Values.envFromSecret }}
        envFrom:
        - secretRef:
            name: {{ .Values.envFromSecret }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
  
  strategy:
    canary:
      # These must match the services generated by the chart
      canaryService: {{ .Release.Name }}-canary
      stableService: {{ .Release.Name }}-stable
      
      trafficRouting:
        nginx:
          # This tells Argo which Ingress to modify during a rollout
          stableIngress: {{ .Values.ingressName }}
          # The domain you are targeting
          additionalIngressAnnotations:
            canary-by-header: X-Canary
            canary-by-header-value: always
      
      steps:
      - setWeight: {{ .Values.canary.initialWeight }}
      - pause: {duration: {{ .Values.canary.initialPause }}}
      - setWeight: {{ .Values.canary.secondWeight }}
      - pause: {duration: {{ .Values.canary.secondPause }}}