apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vsvc
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.host | quote }}
  gateways:
    {{- toYaml .Values.gateways | nindent 4 }}
  http:
    - name: {{ .Release.Name }}-routing-rule  # Argo Rollouts matches this block name
      match:
        - uri:
            prefix: {{ .Values.httpPath }}
      route:
        - destination:
            host: {{ .Release.Name }}-stable.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
          weight: 100
        - destination:
            host: {{ .Release.Name }}-canary.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
          weight: 0